# Generated by Django 6.0.3 on 2026-04-02 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0012_alter_tipoequipamento_options_historicotransferencia'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manutencao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data_manutencao', models.DateField(verbose_name='Data')),
                ('tipo', models.CharField(choices=[('Preventiva', 'Preventiva'), ('Corretiva', 'Corretiva')], max_length=20)),
                ('descricao', models.TextField(verbose_name='O que foi feito')),
                ('prestador', models.CharField(max_length=255, verbose_name='Técnico/Empresa')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Custo (R$)')),
                ('proxima_manutencao', models.DateField(blank=True, null=True, verbose_name='Próxima Revisão')),
                ('status', models.CharField(choices=[('Agendada', 'Agendada'), ('Em Execução', 'Em Execução'), ('Concluída', 'Concluída')], default='Concluída', max_length=20)),
                ('equipamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='manutencoes', to='control.equipamento')),
            ],
            options={
                'ordering': ['-data_manutencao'],
            },
        ),
    ]
