# Generated by Django 6.0.3 on 2026-04-02 20:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('control', '0013_manutencao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='manutencao',
            options={'ordering': ['-data_manutencao'], 'verbose_name': 'Manutenção', 'verbose_name_plural': 'Manutenções'},
        ),
        migrations.AddField(
            model_name='manutencao',
            name='unidade_origem',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='control.unidade'),
        ),
    ]
